### PR TITLE
Added option to create package without importing

### PR DESCRIPTION
**Pull request by panec**

### CODE REVIEW

**Comment by mateuszluczak** [comment]
Please provide usage example

**Comment by panec** [comment]
Potential options to call with -p (none will upload the package):
`ce import -p` - this will create default package `ce-import.zip`
`ce import example.zip -p` - this will create package `example.zip`
`ce import -p example.zip` - this will create package `example.zip`

Potential options to call with -n
`ce import -n example.zip` - this will create package `example.zip` and follow rest of the default steps (push and install)

Potential ways to call this from npm script (with `"scripts": { "package":  "ce import -p" }` inside package.json)
`npm run package -- 'example.zip' - this will create package `example.zip`

**Comment by panec** [comment]
Yes it was tested and is working as expected.

**Comment by toniedzwiedz** [comment]
How's this coming along? We need this feature on our project and I'd rather not use an unmerged feature branch.

**Pull request merged**
